// Category-specific key terms for highlighting in content
// Each category has its own list of important terms to bold

export const CATEGORY_KEY_TERMS: Record<string, string[]> = {
  '1-agent-architecture-design': [
    'Agentic AI',
    'Enterprise AI Factory',
    'Kubernetes',
    'RAG',
    'retrieval-augmented generation',
    'Vector Databases',
    'NeMo',
    'NVIDIA NeMo',
    'NIM',
    'NVIDIA Inference Microservices',
    'TensorRT-LLM',
    'Triton Inference Server',
    'NeMo Guardrails',
    'Agent Intelligence Toolkit',
    'GitOps',
    'Observability',
    'Defense-in-Depth',
    'RBAC',
    'Role-Based Access Control',
    'IAM',
    'Identity and Access Management',
    'Short-term Memory',
    'Long-term Memory',
    'Task Decomposition',
    'Chain of Thought',
    'CoT',
    'ReAct',
    'Reasoning + Acting',
    'Time To First Token',
    'multi-agent systems',
    'orchestration',
    'workflow',
    'container orchestration',
    'GPU resource management',
    'semantic search',
    'embeddings',
    'vector databases',
  ],

  '2-agent-development': [
    'Dynamic Batching',
    'Model Instances',
    'TensorRT',
    'NUMA',
    'Non-Uniform Memory Access',
    'OpenVINO',
    'AIQ',
    'Agent Intelligence Toolkit',
    'RAGAS',
    'Model Context Protocol',
    'MCP',
    'Trajectory Evaluator',
    'Zero-Shot Prompting',
    'Few-Shot Prompting',
    'Chain-of-Thought',
    'CoT',
    'P-Tuning',
    'Prompt Tuning',
    'Virtual Tokens',
    'Vision Language Models',
    'VLMs',
    'Neva 22B',
    'DEOT',
    'NV Embed',
    'Milvus',
    'Global Agent',
    'ZERO_SHOT_REACT_DESCRIPTION',
    'StatefulMemory',
    'Structured Planning',
    'Adaptive Planning',
    'prompt engineering',
    'multimodal',
    'error handling',
    'circuit breaker',
    'retry pattern',
    'transient faults',
  ],

  '3-evaluation-tuning': [
    'Agent Intelligence Toolkit',
    'NeMo Agent Toolkit',
    'Observability',
    'Trace',
    'Span',
    'Offline Evaluation',
    'Online Evaluation',
    'Model Context Protocol',
    'MCP',
    'RAGAS',
    'Agentic AI',
    'Data Flywheel',
    'Model Logic',
    'Reliability',
    'Data Privacy',
    'AI Literacy',
    'Change Champions',
    'Human-in-the-Loop',
    'HITL',
    'Governance',
    'Small Language Models',
    'SLM',
    'Router Models',
    'Response Caching',
    'evaluation',
    'profiling',
    'distributed tracing',
    'OpenTelemetry',
    'judge LLMs',
    'ground truth',
    'A/B testing',
  ],

  '4-deployment-scaling': [
    'Kubernetes',
    'TensorRT-LLM',
    'Triton Inference Server',
    'Horizontal Pod Autoscaler',
    'Queue-to-Compute Ratio',
    'Tensor Parallelism',
    'Pipeline Parallelism',
    'Multi-Instance GPU',
    'MIG',
    'FP8 Precision',
    'GitOps',
    'Artifact Repository',
    'Observability',
    'Time To First Token',
    'Tokens Per Second',
    'Nsight Systems',
    'Prometheus',
    'Service Mesh',
    'RBAC',
    'Role-Based Access Control',
    'Model Context Protocol',
    'MCP',
    'Ingress',
    'container orchestration',
    'autoscaling',
    'dynamic batching',
    'quantization',
    'performance optimization',
  ],

  '5-cognition-planning-memory': [
    'AI Memory',
    'Short-Term Memory',
    'STM',
    'Long-Term Memory',
    'LTM',
    'Episodic Memory',
    'Semantic Memory',
    'Procedural Memory',
    'Parametric Memory',
    'Non-Parametric Memory',
    'Retrieval-Augmented Generation',
    'RAG',
    'Planning',
    'Reinforcement Learning',
    'Context Window',
    'Prompt Caching',
    'Knowledge Editing',
    'Multi-Turn Dialogue',
    'Vector Embeddings',
    'Knowledge Graph',
    'Memory Consolidation',
    'Personalization',
    'NeMo',
    'NVIDIA NeMo',
    'memory systems',
    'cognitive capabilities',
    'reasoning',
    'adaptation',
  ],

  '6-knowledge-integration-data-handling': [
    'Retrieval-Augmented Generation',
    'RAG',
    'Fine-Tuning',
    'Vector Database',
    'Embedding',
    'Semantic Search',
    'Approximate Nearest Neighbors',
    'ANN',
    'FAISS',
    'ChromaDB',
    'Query Embedding',
    'Context Integration',
    'Parameter-Efficient Fine-Tuning',
    'Low-Rank Adaptation',
    'LoRA',
    'Quantized LoRA',
    'Retrieval-Augmented Fine-Tuning',
    'RAFT',
    'Source Attribution',
    'Ground Truth',
    'Context Window',
    'Knowledge Base',
    'vector embeddings',
    'semantic similarity',
    'knowledge integration',
  ],

  '7-NVDA-Platform-Integration': [
    'TensorRT',
    'Triton Inference Server',
    'NeMo Guardrails',
    'NeMo Agent Toolkit',
    'NIM',
    'NVIDIA Inference Microservices',
    'Dynamic Batching',
    'Layer Fusion',
    'Quantization',
    'CUDA Graphs',
    'Multi-Streaming',
    'Model Instance',
    'OpenTelemetry',
    'Model Context Protocol',
    'MCP',
    'YAML Configuration',
    'Hyperparameter Optimization',
    'Profiling',
    'Tool Registry',
    'Framework Interoperability',
    'Microservice Architecture',
    'Edge Deployment',
    'NVIDIA platform',
    'inference optimization',
    'performance tuning',
  ],

  '8-run-monitor-maintain': [
    'Observability',
    'Trace Correlation',
    'Trace ID',
    'Metadata Extraction',
    'Request Interception',
    'Model Monitoring',
    'Data Drift',
    'Model Drift',
    'Functional Monitoring',
    'Operational Monitoring',
    'Time-Weighted Retrieval',
    'Temporal Decay',
    'Access-Based Tracking',
    'Troubleshooting',
    'Response Caching',
    'Semantic Similarity Matching',
    'Automatic Retry',
    'Exponential Backoff',
    'Performance Profiling',
    'Resource Tracking',
    'logging',
    'tracing',
    'monitoring',
    'debugging',
  ],

  '9-Safety-Ethics': [
    'Responsible AI',
    'Guardrails',
    'Input Validation',
    'Output Filtering',
    'Prompt Injection',
    'Jailbreak Detection',
    'Fact-Checking',
    'Sensitive Information Masking',
    'Content Moderation',
    'Bias Mitigation',
    'Fairness Assessment',
    'Transparency',
    'Accountability',
    'Human Oversight',
    'Regulatory Compliance',
    'Data Protection',
    'Algorithmic Transparency',
    'Safety Assurance',
    'Predetermined Change Control Plans',
    'Modification Review',
    'safety',
    'ethics',
    'compliance',
    'security',
  ],

  '10-Human-AI-Interaction': [
    'Human-in-the-Loop',
    'HITL',
    'LangGraph',
    'Interrupt Nodes',
    'Humans as Tools',
    'Data Flywheel',
    'Continuous Improvement',
    'Institutional Knowledge',
    'Tiered Oversight',
    'Explainable AI',
    'XAI',
    'Audit Trails',
    'Adaptive Autonomy',
    'Reinforcement Learning from Human Feedback',
    'RLHF',
    'Bias Mitigation',
    'Real-Time Error Correction',
    'Strategic Oversight',
    'Feedback Loops',
    'Human-AI Collaboration',
    'Augmented Intelligence',
    'Selective Engagement',
    'Workflow Continuity',
    'human oversight',
    'collaboration',
  ],
};

// Helper function to extract category from file path
export function getCategoryFromPath(filePath: string): string | null {
  // Extract category from paths like:
  // "1-agent-architecture-design/review.txt"
  // "summaries/1-agent-architecture-design/review.txt"
  // "app/data/content/summaries/1-agent-architecture-design/review.txt"
  // "1-agent-architecture-design/1-agentic-AI-factory.txt"
  
  // First try to match pattern: number-dash-text (category pattern)
  const match = filePath.match(/(\d+-[^/\s]+)/);
  if (match) {
    const category = match[1];
    // Verify it's a known category
    if (CATEGORY_KEY_TERMS[category]) {
      return category;
    }
  }
  
  // Try alternative patterns with summaries/content prefix
  const altMatch = filePath.match(/(?:summaries|content)[/\\](\d+-[^/\\\s]+)/);
  if (altMatch) {
    const category = altMatch[1];
    if (CATEGORY_KEY_TERMS[category]) {
      return category;
    }
  }
  
  return null;
}

// Get key terms for a specific category
export function getKeyTermsForCategory(category: string | null): string[] {
  if (!category) {
    // Return a minimal global list if category can't be determined
    return [
      'Agentic AI',
      'Enterprise AI Factory',
      'RAG',
      'retrieval-augmented generation',
    ];
  }
  
  return CATEGORY_KEY_TERMS[category] || [];
}
